#
# Gordon Taskqueue Config
#

# Redis server address
redis_address = "127.0.0.1:6379"

# Redis network-type (default is "tcp")
# redis_network = "tcp"

# Queue key, which is basically a prefix for all used redis-keys.
queue_key = "taskqueue"

# Path to a script that is executed when a task failed.
# The script receives the full path to a temporary file as the first parameter,
# which contains the output of the failed task. It will be removed by Gordon
# after the execution of this script.
# If commented or an empty string, this functionality is disabled.
# error_script = "/opt/sendErrorNotification.py"

# The global time-to-live value (in seconds) for the lists that are storing failed tasks.
# If commented or set to 0, this functionality is disabled.
# This value can also be overridden (a value greater than 0) on task-level.
failed_tasks_ttl = 172800

# Logfile which is used instead of stdout.
# If commented or an empty string, no logfile will be used.
# logfile = "/var/log/gordon.log"

# Directory which is used for temporary files.
# If commented or an empty string, the system-default will be used.
# temp_dir = "/tmp"

# Check internal settings
# These values define how often the application will look for new tasks. When no
# new tasks were found the interval is increased by the defined values (minimum value
# and factor). When at least on task is found again the interval will be reset to the minium.

# The miminum check-interval for new tasks, in ms.
interval_min = 250
# The maximum check-interval for new tasks, in ms.
interval_max = 30000
# The multiplicator of the minimum interval when no new tasks were found, as float.
interval_factor = 2.0

# Error backoff settings (global)
# The values here are applied to all tasks, unless specified (a value greater than 0)
# on task-level, except for backoff_enabled. If `backoff_enabled = true`, it will
# be enabled for all tasks regardless of their individual backoff_enabled setting.

# Uncomment or set this value to false, to disable the error-backoff functionality for all tasks.
backoff_enabled = true
# The minimum time to wait after a task failed, in ms.
backoff_min = 250
# The maxiumum time to wait after a task failed, in ms.
backoff_max = 20000
# The multiplicator of the minimum time with every additional failed task, as float.
backoff_factor = 2.0

# Statistics related settings
[stats]
# Interface where a webservice will listen on.
# If commented or an empty string, no webservice will be created.
# interface = "127.0.0.1:8080"

# Url pattern where the statistics-webservice will respond to
pattern = "/"

# Certificate settings for the statistics-webservice.
# If these are defined https will be used, otherweise http.
# tls_cert_file = "/etc/ssl/private/certificate.crt"
# tls_key_file = "/etc/ssl/private/private.key"

# NewRelic agent related settings
# As this is currently in beta-state, you'll need to request a beta-token on their website.
# (uncomment and define those values accordingly to enable it)
#[stats.newrelic]
#license = "8fb744b51a1f14e5e8cda4e4aec68e2f"
#beta_token = "8fb744b51a1f14e5e8cda4e4aec68e2f"
#app_name = "Gordon Taskqueue"

# Task related tables
[tasks]

# This table configures a task with the type 'something'.
# Just create a new table for every task you want to handle,
# and adjust their type & script-paths accordingly.
[tasks.something]
script = "/opt/something.php"
# workers = 2
